# Generated by Django 5.0.6 on 2024-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_moviedata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.png', upload_to='Image/'),
        ),
    ]
